# ---------------------------------
# ThreadSanitizer suppression file.
# ---------------------------------

# libdbus-1.so is used by SDL3 and is not thread-safe.
mutex:libdbus-1.so
race:libdbus-1.so.3
mutex:libdbus-1.so.3
deadlock:libdbus-1.so.3
