using System.Text;
using LumenBuilder.Build;
using LumenBuilder.Build.Toolchain;
using LumenBuilder.Common;
using LumenBuilder.Model;

namespace LumenBuilder.Emit.Ninja;

/// <summary>
/// Emits Ninja build files.
/// </summary>
public sealed class NinjaWriter
{
    private readonly BuildContext Context;
    private readonly Compiler Toolchain;

    public NinjaWriter(BuildContext Context)
    {
        this.Context = Context;
        this.Toolchain = Context.Toolchain;
    }

    public string Generate(BuildPlan Plan)
    {
        var Sb = new StringBuilder();

        Sb.AppendLine("# Generated by LumenBuilder");
        Sb.AppendLine($"# Configuration: {Context.Configuration}");
        Sb.AppendLine();

        WriteRules(Sb);
        Sb.AppendLine();

        WriteCompileStatements(Sb, Plan);
        Sb.AppendLine();

        WriteLinkStatements(Sb, Plan);

        return Sb.ToString();
    }

    public void Write(string OutputPath, BuildPlan Plan)
    {
        EmitHelpers.WriteToFile(OutputPath, Generate(Plan));
    }

    private void WriteRules(StringBuilder Sb)
    {
        Sb.AppendLine($"cxx = {Toolchain.CompilerPath}");
        Sb.AppendLine($"ar = {Toolchain.ArchiverPath}");

        if (Context.Platform.Type == PlatformType.Windows)
        {
            Sb.AppendLine("mkdir_cmd = cmd /c if not exist $out_dir mkdir $out_dir");
        }
        Sb.AppendLine();

        Sb.AppendLine("rule compile");
        Sb.AppendLine("  command = $cxx $cflags -c -o $out $in");
        Sb.AppendLine("  description = Compiling $in");
        Sb.AppendLine();

        Sb.AppendLine("rule link");
        Sb.AppendLine("  command = $cxx $ldflags -o $out $in $libs");
        Sb.AppendLine("  description = Linking $out");
        Sb.AppendLine();

        Sb.AppendLine("rule archive");
        Sb.AppendLine($"  command = $ar {Toolchain.ArchiveFlags} $out $in");
        Sb.AppendLine("  description = Archiving $out");
    }

    private void WriteCompileStatements(StringBuilder Sb, BuildPlan Plan)
    {
        string CompileFlags = Toolchain.GetCompileFlags(Context.Configuration);

        Sb.AppendLine("# Compile statements");

        for (int Index = 0; Index < Plan.CompileUnits.Count; ++Index)
        {
            var Unit = Plan.CompileUnits[Index];

            Sb.Append("build ");
            Sb.Append(EscapePath(Unit.ObjectFile));
            Sb.Append(": compile ");
            Sb.AppendLine(EscapePath(Unit.SourceFile));

            Sb.Append("  cflags = ");
            Sb.Append(CompileFlags);

            CompilerHelpers.AppendPrefixedQuoted(Sb, Unit.Includes, Toolchain.IncludePrefix);
            CompilerHelpers.AppendPrefixed(Sb, Unit.Defines, Toolchain.DefinePrefix);

            Sb.AppendLine();
        }
    }

    private void WriteLinkStatements(StringBuilder Sb, BuildPlan Plan)
    {
        Sb.AppendLine("# Link statements");

        for (int Index = 0; Index < Plan.LinkTargets.Count; ++Index)
        {
            var Target = Plan.LinkTargets[Index];
            string Rule = Target.Type == ModuleType.StaticLibrary ? "archive" : "link";

            Sb.Append("build ");
            Sb.Append(EscapePath(Target.OutputFile));
            Sb.Append(": ");
            Sb.Append(Rule);

            AppendEscapedPaths(Sb, Target.ObjectFiles);

            if (Target.DependencyPaths.Count > 0)
            {
                Sb.Append(" |");
                AppendEscapedPaths(Sb, Target.DependencyPaths);
            }

            Sb.AppendLine();

            if (Target.Type != ModuleType.StaticLibrary)
            {
                Sb.Append("  libs =");
                CompilerHelpers.AppendQuotedPaths(Sb, Target.DependencyPaths);
                CompilerHelpers.AppendPrefixed(Sb, Target.SystemLibraries, Toolchain.LibraryPrefix);
                Sb.AppendLine();
            }

            if (Target.Type != ModuleType.StaticLibrary)
            {
                Sb.Append("  ldflags =");
                if (!string.IsNullOrEmpty(Toolchain.LinkerFlag))
                {
                    Sb.Append(' ');
                    Sb.Append(Toolchain.LinkerFlag);
                }
                if (Target.Type == ModuleType.SharedLibrary)
                {
                    Sb.Append(' ');
                    Sb.Append(Toolchain.SharedFlag);
                }
                CompilerHelpers.AppendPrefixedQuoted(Sb, Target.LibraryPaths, Toolchain.LibraryPathPrefix);
                Sb.AppendLine();
            }
        }

        Sb.AppendLine();
        Sb.Append("build all: phony");
        for (int Index = 0; Index < Plan.LinkTargets.Count; ++Index)
        {
            Sb.Append(' ');
            Sb.Append(EscapePath(Plan.LinkTargets[Index].OutputFile));
        }
        Sb.AppendLine();
        Sb.AppendLine("default all");
    }

    private static void AppendEscapedPaths(StringBuilder Sb, IReadOnlyList<string> Paths)
    {
        for (int Index = 0; Index < Paths.Count; ++Index)
        {
            Sb.Append(' ');
            Sb.Append(EscapePath(Paths[Index]));
        }
    }

    private static string EscapePath(string Path)
    {
        return Path.Replace(" ", "$ ").Replace(":", "$:");
    }
}
