using System.Text;
using LumenBuilder.Build;
using LumenBuilder.Build.Toolchain;
using LumenBuilder.Common;
using LumenBuilder.Model;

namespace LumenBuilder.Emit.Makefile;

/// <summary>
/// Emits GNU Makefile build files.
/// </summary>
public sealed class MakefileWriter
{
    private readonly BuildContext Context;
    private readonly Compiler Toolchain;

    public MakefileWriter(BuildContext Context)
    {
        this.Context = Context;
        this.Toolchain = Context.Toolchain;
    }

    public string Generate(BuildPlan Plan)
    {
        var Sb = new StringBuilder();

        Sb.AppendLine("# Generated by LumenBuilder");
        Sb.AppendLine($"# Configuration: {Context.Configuration}");
        Sb.AppendLine();

        WriteVariables(Sb);
        Sb.AppendLine();

        WritePhonyTargets(Sb, Plan);
        Sb.AppendLine();

        WriteLinkTargets(Sb, Plan);
        Sb.AppendLine();

        WriteCompileTargets(Sb, Plan);

        WriteCleanTarget(Sb);

        return Sb.ToString();
    }

    public void Write(string OutputPath, BuildPlan Plan)
    {
        EmitHelpers.WriteToFile(OutputPath, Generate(Plan));
    }

    private void WriteVariables(StringBuilder Sb)
    {
        bool IsWindows = Context.Platform.Type == PlatformType.Windows;

        Sb.AppendLine($"CXX := {Toolchain.CompilerPath}");
        Sb.AppendLine($"AR := {Toolchain.ArchiverPath}");
        Sb.AppendLine($"CXXFLAGS := {Toolchain.GetCompileFlags(Context.Configuration)}");
        string LinkerFlag = Toolchain.LinkerFlag;
        Sb.AppendLine(string.IsNullOrEmpty(LinkerFlag) ? "LDFLAGS :=" : $"LDFLAGS := {LinkerFlag}");
        Sb.AppendLine();

        if (IsWindows)
        {
            Sb.AppendLine("MKDIR = if not exist $(subst /,\\,$(dir $@)) mkdir $(subst /,\\,$(dir $@))");
            Sb.AppendLine("RM = del /F /Q");
            Sb.AppendLine("RMDIR = rmdir /S /Q");
        }
        else
        {
            Sb.AppendLine("MKDIR = @mkdir -p $(dir $@)");
            Sb.AppendLine("RM = rm -f");
            Sb.AppendLine("RMDIR = rm -rf");
        }
    }

    private void WritePhonyTargets(StringBuilder Sb, BuildPlan Plan)
    {
        Sb.Append(".PHONY: all clean");
        for (int Index = 0; Index < Plan.BuildOrder.Count; ++Index)
        {
            Sb.Append(' ');
            Sb.Append(Plan.BuildOrder[Index]);
        }
        Sb.AppendLine();
        Sb.AppendLine();

        Sb.Append("all:");
        for (int Index = 0; Index < Plan.LinkTargets.Count; ++Index)
        {
            Sb.Append(' ');
            Sb.Append(Plan.LinkTargets[Index].OutputFile);
        }
        Sb.AppendLine();
    }

    private void WriteLinkTargets(StringBuilder Sb, BuildPlan Plan)
    {
        for (int Index = 0; Index < Plan.LinkTargets.Count; ++Index)
        {
            var Target = Plan.LinkTargets[Index];

            Sb.Append(Target.OutputFile);
            Sb.Append(':');

            for (int ObjIndex = 0; ObjIndex < Target.ObjectFiles.Count; ++ObjIndex)
            {
                Sb.Append(' ');
                Sb.Append(Target.ObjectFiles[ObjIndex]);
            }

            for (int DepIndex = 0; DepIndex < Target.DependencyPaths.Count; ++DepIndex)
            {
                Sb.Append(' ');
                Sb.Append(Target.DependencyPaths[DepIndex]);
            }

            Sb.AppendLine();

            Sb.Append('\t');
            Sb.AppendLine("$(MKDIR)");

            Sb.Append('\t');
            if (Target.Type == ModuleType.StaticLibrary)
            {
                Sb.Append($"$(AR) {Toolchain.ArchiveFlags} $@");
                for (int ObjIndex = 0; ObjIndex < Target.ObjectFiles.Count; ++ObjIndex)
                {
                    Sb.Append(' ');
                    Sb.Append(Target.ObjectFiles[ObjIndex]);
                }
            }
            else
            {
                Sb.Append("$(CXX) $(LDFLAGS)");
                if (Target.Type == ModuleType.SharedLibrary)
                {
                    Sb.Append(' ');
                    Sb.Append(Toolchain.SharedFlag);
                }
                Sb.Append(" -o $@");
                for (int ObjIndex = 0; ObjIndex < Target.ObjectFiles.Count; ++ObjIndex)
                {
                    Sb.Append(' ');
                    Sb.Append(Target.ObjectFiles[ObjIndex]);
                }
                CompilerHelpers.AppendQuotedPaths(Sb, Target.DependencyPaths);
                CompilerHelpers.AppendPrefixedQuoted(Sb, Target.LibraryPaths, Toolchain.LibraryPathPrefix);
                CompilerHelpers.AppendPrefixed(Sb, Target.SystemLibraries, Toolchain.LibraryPrefix);
            }
            Sb.AppendLine();
            Sb.AppendLine();
        }
    }

    private void WriteCompileTargets(StringBuilder Sb, BuildPlan Plan)
    {
        for (int Index = 0; Index < Plan.CompileUnits.Count; ++Index)
        {
            var Unit = Plan.CompileUnits[Index];

            Sb.Append(Unit.ObjectFile);
            Sb.Append(": ");
            Sb.AppendLine(Unit.SourceFile);

            Sb.Append('\t');
            Sb.AppendLine("$(MKDIR)");

            Sb.Append('\t');
            Sb.Append("$(CXX) $(CXXFLAGS)");

            CompilerHelpers.AppendPrefixedQuoted(Sb, Unit.Includes, Toolchain.IncludePrefix);
            CompilerHelpers.AppendPrefixed(Sb, Unit.Defines, Toolchain.DefinePrefix);

            Sb.AppendLine(" -c -o $@ $<");
            Sb.AppendLine();
        }
    }

    private void WriteCleanTarget(StringBuilder Sb)
    {
        Sb.AppendLine("clean:");
        bool IsWindows = Context.Platform.Type == PlatformType.Windows;

        if (IsWindows)
        {
            Sb.AppendLine($"\tif exist {Paths.IntermediateDir} $(RMDIR) {Paths.IntermediateDir.Replace("/", "\\")}");
            Sb.AppendLine($"\tif exist {Paths.BinariesDir} $(RMDIR) {Paths.BinariesDir.Replace("/", "\\")}");
        }
        else
        {
            Sb.AppendLine($"\t$(RMDIR) {Paths.IntermediateDir} {Paths.BinariesDir}");
        }
    }
}
