name: WindowsBuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    name: BuildAndTest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: InstallSystemDependencies
        run: |
          choco install ninja cmake

      - name: CacheVendor
        id: vendor-cache
        uses: actions/cache@v4
        with:
          path: Vendor
          key: Vendor-${{ runner.os }}-${{ hashFiles('Scripts/Dependencies/**/*.rb') }}

      - name: InstallDependencies
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ruby Scripts/Dependencies/InstallDependencies.rb

      - name: SetupDotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.100"

      - name: CacheNuGet
        id: nuget-cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: RunBuilder Ninja
        run: dotnet run --project Builder/Builder.csproj -- build --format ninja --config release

      - name: RunBuilder CMake
        run: dotnet run --project Builder/Builder.csproj -- build --format cmake --config release

      - name: Build Ninja
        run: ninja

      - name: Check & Clean Ninja
        shell: pwsh
        run: |
          if (Test-Path "Binaries/BaseExample/BaseExample.exe") {
            Write-Host "Ninja build successful"
            ninja -t clean
          } else {
            Write-Error "Ninja build failed: Executable not found"
            exit 84
          }

      - name: Build CMake
        run: |
          cmake .
          cmake --build . --config Release

      - name: Check & Clean CMake
        shell: pwsh
        run: |
          if (Test-Path "Binaries/BaseExample/BaseExample.exe") {
            Write-Host "CMake build successful"
            cmake --build . --target clean
          } else {
            Write-Error "CMake build failed: Executable not found"
            exit 84
          }
